### ISSUE TITLE
Demo broken

### ISSUE THREAD

**Issue by ghost** [katejeffreys/start-polymer3#15]
Android chrome browser evergreen.
When I click I like pie the screen freezes.

**Comment by ghost** [comment]
Thanks. I'm trying to figure out whether this is an issue with `paper-checkbox` interacting with a mobile device. Can you let me know if you get the same effect with the checkboxes on the [paper-checkbox demo page](https://www.webcomponents.org/element/PolymerElements/paper-checkbox/demo/demo/index.html)?

**Comment by ghost** [comment]
Hrmm so if you saw the same behavior I did, I'm guessing the page didn't actually freeze. What happened for me is when I tapped the checkbox or checkbox label on my mobile device, the style that was applied to show that the element received focus looked similar to a frozen `paper-ripple` animation. Everything else was fine, and the "you like pie" hidden message was revealed as expected.

I changed the focus styles a bit (although it's probably not best practice to obscure the fact that the element received focus, so maybe needs another solution idk..). @gedw99 Can you let me know if it still freezes for you?

**Comment by Nditah** [comment]
Please it will be nice if you make one complete tutorial with Polymer 3 that reflects the updated features.

**Comment by ghost** [comment]
@Nditah In progress!
