### ISSUE TITLE
No Typescript?

### ISSUE THREAD

**Issue by mcalthrop** [katejeffreys/start-polymer3#16]
Hi. Thanks for the sample app.

Just wondering why there’s no Typescript in this codebase? My impression was that moving to TS was a key advantage of Polymer 3 over Polymer 2.

**Comment by JosefJezek** [comment]
Typescript is not part of the platform. ;-)

**Comment by mcalthrop** [comment]
Ah yes… reading through the docs I can see that now. 

Any repos you could point me towards? Strong typing is that much better than ES6. :-)

**Comment by ghost** [comment]
Thanks for your interest! Here's a Polymer 3/typescript app I found: https://github.com/chybie/poly-mini-game

Closing this issue for now. I might re-write the sample with typescript if priorities permit :)
