### ISSUE TITLE
"Could not render the custom element" message appears despite Javascript being enabled

### ISSUE THREAD

**Issue by panchalkalpesh** [katejeffreys/start-polymer3#26]
Despite having JavaScript enabled on the browser, we still see the following message `<start-polymer3>` is being rendered.

![image](https://user-images.githubusercontent.com/1808686/43484419-4c01d37e-94dc-11e8-9f29-2871c4655e1f.png)

Browser: [Chromium ](https://www.chromium.org/Home) Version 67.0.3396.99 (64-bit)

**Comment by ghost** [comment]
Thanks :)
